### ISSUE TITLE
just wanted to say thanks

### ISSUE THREAD

**Issue by kristopolous** [eddelbuettel/pkg-fonts-source-code-pro#1]
This thing worked perfectly. Appreciated.

**Comment by eddelbuettel** [comment]
:heart: 

These font packages made my day too at points in time.  For some. the distro caught up.   Also for what it is worth, I am on the jetbrains one.  Works nicely for me.

**Comment by kristopolous** [comment]
i didn't even check ... apparently it's in texlive-fonts-extra ... might be a good idea to mention it somewhere.

**Comment by eddelbuettel** [comment]
Yes well the '7 years without commits' is a bit of a hint :grinning: 

I use them as desktop fonts in editor and terminal and there is an abundance of riches of `fonts-*` now. I see 527 packages in Ubuntu 23.04.
